### PR TITLE
Make the systemd unit file more standard

### PR DESCRIPTION
**Pull request by strugee**
This PR changes the systemd unit file to be more standard.

I recognize that some of these changes may be rejected, so I've been careful to separate each change into its own commit. Also, the extended commit messages have justifications for each change.

### CODE REVIEW

**Comment by jpmens** [comment]
@strugee I'll look at this (any any code you PR) when I can test it, which will be towards the end of the month earliest.

In particular I don't want the `fpm` packaging to break

**Comment by strugee** [comment]
@jpmens no problem, thanks for the heads up. FWIW I'm running something very similar to this on my production Debian Jessie system.

What's `fpm`?

**Comment by jpmens** [comment]
`fpm` is the ["fine" package manager](https://github.com/jordansissel/fpm/wiki) which I use to create CentOS & Debian packages (see `etc/debian/` and `etc/centos/`). Background: I chose this as the easiest way to build packages. Since then somebody contributed Debian native packaging, but I haven't studied that at all.

**Comment by strugee** [comment]
Gotcha, thanks.

**Comment by strugee** [comment]
@jpmens ping?

**Comment by jpmens** [comment]
Merged, thank you. I have removed passing topic from the systemd unit file as this topic was wrong (it ought to have been `owntracks/#`) and it's read by the Recorder from the defaults file anyway.

**Comment by strugee** [comment]
Cool, thanks!

**Pull request merged**
