### PR TITLE
New homepage

### PR DESCRIPTION
**Pull request by edautz**
As promised!

### CODE REVIEW

**Comment by jpmens** [comment]
Thank you for the submission which I'm looking at now.

As can be seen from this screenshot, I don't get a list of users shown, neither with Safari, Firefox, nor with Chrome. Neither browser shows an error message in the console.

What do you think this is due to?

jmbp-4539

**Comment by jpmens** [comment]
In  1d90c4b you have created `index.html` which I think is unintentional; it ought to be `docroot/index.html` (at least the diff looks as though it should be that file).

**Comment by edautz** [comment]
The index.html file from 1d90c4b is the last and the best one. The former ones contains several little bugs.

Strange that your userlist is not created. On my Win7 machine it runs fine also on my apple devices. It is not tested on win10.

Lookes like the following part of the code is not executed when loading the page or this part of the code is not gaining any data.

The first part of the code gets the output of /api/0/last, and creates two arrays:
        var user =[];
        var device =[];
and fills them with the extracted users array and devices array from /api/0/last output.

After this step, a loop creates the corresponding radio buttons for the users and devices.

Please put a debugger; statement in the code, and check if user[] and device[] array's are filled with your users and devices.

+      <script>
+        //fetch user/device from url 
+        document.getElementById('error3').innerHTML = "";
+        //var dataURI = "http://192.168.2.113:8083/api/0/last";
+        var dataURI = "/api/0/last";
+        var Httpreq = new XMLHttpRequest(); // a new request
+        Httpreq.open("GET",dataURI,false);
+        Httpreq.send(null);
+        var urldata = Httpreq.responseText;          
+        if (urldata.length < 3) document.getElementById('error3').innerHTML = "OT-recorder user data couldn't be loaded";
+        //parsing users en devices
+        var stringpointer = 0;
+        var beginposdev;
+        var endposdev;
+        var user =[];
+        var device =[];
+        var index = 0;
+        // get users and devices
+        while (stringpointer < urldata.length) {
+          beginposus = urldata.indexOf("user", stringpointer);
+          beginposdev = urldata.indexOf("device", beginposus);
+          endposdev = urldata.indexOf("fulldate", beginposdev);
+          if (stringpointer < endposdev) stringpointer = endposdev;
+          else { break; }   
+          user[index] = urldata.substr((beginposus+11),(beginposdev-beginposus-14));
+          device[index] = urldata.substr((beginposdev+9),(endposdev-beginposdev-12));
+          index ++;
+        }
+
+
+        //build user/device radio button list
+        var radio_home = document.getElementById("usertable");
+        function makeRadioButton(name, useriddeviceid, useriddeviceidinput) {
+          var label = document.createElement("label");
+          var radio = document.createElement("input");
+          radio.type = "radio";
+          radio.id = useriddeviceid;
+          radio.setAttribute("name" , "device");
+          radio.setAttribute("onclick", "selectDevice()");     
+          label.appendChild(radio);
+          label.appendChild(document.createTextNode(useriddeviceid));
+          return label;
+        }
+        var userdevice_button;
+        var i;
+        for (i = 0; i < user.length; i++) {
+          userdevice_button = makeRadioButton("device", user[i] + "/" + device[i], user[i] + "/" + device[i]);
+          radio_home.appendChild(userdevice_button);
+          radio_home.innerHTML += "<br>";
+       }
+      </script>

**Comment by edautz** [comment]
Testen my version on a win10 machine using Chrome and IE11. Runs without problems.

I think your content of api/0/last is different and my program is not capable to handle that. Can you provide your version? So I can solve that.

**Comment by jpmens** [comment]
It cannot be different if you are using a rather current version of Recorder.

Also: please address the issue of `index.html` being in the wrong directory; it should be in `docroot/` and not in the root of the project (as mentioned above already).

I probably won't be able to work on this for the next weeks.

**Comment by edautz** [comment]
Index.html location fixed.

I am using one of the lastest version of ot recorder, version 0.7.6-16-g7a1562e24e.

But I am not using the owntrack app for the location information, but iCloud information and a custom build car tracking device with a gps reciever. The mapping and translation of the incoming data of these devices is done with Nodered and the results are fed with mqtt to ot-recorder.

I had to experiment with datafields to determine wich fields were nessecary for OT recorder, I use the user, device and fulldate fields in this order to extract the user and device information in the index.html file.

If your fields are in another order or other fields are between them, my mechanism will not work and this could result in an empty user/device list.

So for me it make sense to get a copy of your api/0/last data. So I can check this, and if so, modify my dataorder and index.html that this complies to your standard.

**Comment by lennardk** [comment]
@edautz fwiw, the userlist works for me if I use 'username', 'device' and 'ghash' for finding the string positions.
That being said, it doesn't feel very robust to depend on these fields being all present and in this specific order in the message. Wouldn't it be easier to just pull the response through a JSON parser and directly access the fields?

**Comment by edautz** [comment]
Made the index.html file user and device discovery indepent of the order of the fields. Just the fields user and devices has to be present in the /api/0/last file.

**Comment by lennardk** [comment]
for me, the field is "username", but the current code does match that so it's fine. You just have a typo on line 61; if I understand what you're doing correctly:
-          if (endposdev < endposus) biggest = endpondus;
+          if (endposdev < endposus) biggest = endposus;

**Comment by edautz** [comment]
Fixed typo. Can you confirm the standard name of the field is username instead of user?

I got my information of the fields from: 

https://owntracks.org/booklet/tech/json/

There its called user.

**Comment by edautz** [comment]
Very clear. I have change that. But I have to check the impact in my nodered setup because I made a mapping to user instead of username.

I will look into it when I got some spare time.

**Comment by edautz** [comment]
I think the code is robust now and working now for all kinds of field order. I choose to use plain javascript and only use a third party calender tool, because not reinvent the wheel. I change the search for user to username for clearness. I am only a hobby programmer putting a lot of effort to make a more usefull homepage.

**Comment by edautz** [comment]
I like your project very much, and use it several weeks now with great pleasure as viewing part of my car and telephone tracking system.

I regret to see that my effort doesn’t meet your standards. 

I am afraid I can’t comply to your request because as a hobby programmer I don’t have skills to make your requested changes. Maybe a more skilled programmer can make the required changes to comply to your code quality standards. 

I only can say that this new homepage runs stable without any problems in my setup.

**Comment by jpmens** [comment]
@edautz thank you for your work and your attempted contribution; very much appreciated. 
I will now close this in favor of a possible solution via #284

**Pull request closed without merging**
