### PR TITLE
Reorganize README

### PR DESCRIPTION
**Pull request by strugee**
Followup to #134

This is currently a work-in-progress (so don't merge), but I wanted to open this PR early so I don't forget to call out 3e25dbc3a5be82330cfa393dad9f6a45931911f7 as a semi-significant change to content.

### CODE REVIEW

**Comment by jpmens** [comment]
Leave it as is, @strugee; I'll survive. ;-)

**Comment by strugee** [comment]
OK, I think I've done a pretty good job cleaning this up. It could still use improvement, but I won't have much time to work on it in the near future, so better to merge this now.

I would strongly suggest that when #135 is fixed the corresponding README documentation should be removed, simply because the README is so long as it is and anything that can be removed _should_ be removed in order to make it more understandable/less intimidating. I'd also submit that this project could benefit from a separate ReadTheDocs repo.

**Comment by strugee** [comment]
@jpmens will this have to wait until the end of the month too? Asking since it's strictly a documentation change.

**Comment by jpmens** [comment]
Give mea few hours to recover from travels, and I'll look. :-)

**Comment by jpmens** [comment]
Thank you very much, @strugee! Merged.

**Comment by strugee** [comment]
@jpmens happy to help! Thanks for reviewing :)

**Pull request merged**
